name: Deploy Javadoc to GitHub Pages

on:
  push:
    branches:
      - JMEOS-working

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Maven
        run: mvn -B wrapper:wrapper

      - name: Generate Javadoc
        run: mvn -B javadoc:javadoc
        # By default, this generates Javadoc in the target/site/apidocs/ directory

      - name: Deploy Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
          # This deploys the generated Javadoc from target/site/apidocs to the gh-pages branch
